// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9sYj1qDMUboUq2aL8GEl-b7MBu1jpRrA',
    appId: '1:435427114035:web:e224d607fda3de84e7b746',
    messagingSenderId: '435427114035',
    projectId: 'ovrsr-6bcbe',
    authDomain: 'ovrsr-6bcbe.firebaseapp.com',
    storageBucket: 'ovrsr-6bcbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNOcfsRtoLYd0akYV-054DBxKE1glV7x4',
    appId: '1:435427114035:android:b16416090e746e70e7b746',
    messagingSenderId: '435427114035',
    projectId: 'ovrsr-6bcbe',
    storageBucket: 'ovrsr-6bcbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0I1ExMyZILIiGklaN1Re5nJ1-Iw7oTk',
    appId: '1:435427114035:ios:0052982f7135e7a9e7b746',
    messagingSenderId: '435427114035',
    projectId: 'ovrsr-6bcbe',
    storageBucket: 'ovrsr-6bcbe.appspot.com',
    iosBundleId: 'com.example.ovrsr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0I1ExMyZILIiGklaN1Re5nJ1-Iw7oTk',
    appId: '1:435427114035:ios:b699253d1138bec0e7b746',
    messagingSenderId: '435427114035',
    projectId: 'ovrsr-6bcbe',
    storageBucket: 'ovrsr-6bcbe.appspot.com',
    //iosBundleId: 'com.example.ovrsr.RunnerTests',
    iosBundleId: 'com.example.ovrsr',
  );
}
